apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  call_with_env:    
    uses: mluzcabrera/platformteamrepo001/.cloudbees/workflows/rw-privateimage.yaml
