apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  pre_prod:
    environment: environment_mlcb
    steps:
      - name: mystep
        uses: docker://alpine:3.17
        run: echo ${{cloudbees.api.token }} > $CLOUDBEES_OUTPUTS/token
    outputs:
      token: ${{ steps.mystep.outputs.token }}
  echo:
    needs: pre_prod
    steps:
      - name: echo
        uses: docker://alpine:3.17
        run: echo ${{needs.preprod.token}} 
    
 