apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test properties resolution reusable 2
on:
  workflow_call:
   secrets:
    token:
      required: false
jobs:
   with_environment_mlcb:
    # environment: environment_mlcb
    steps:
      - name: Print properties
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo " ${{ secrets.token }}" 
          string="${{secret.token}}"
          new_string=$(echo "$string" | sed 's/o/a/g')
          echo "$new_string"  # Output: "hella warld"