apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test properties resolution reusable 2
on:
  workflow_call:

jobs:
   with_environment_mlcb:
    # environment: environment_mlcb
    steps:
      - name: Print properties
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Property testpropertymlcb  should be 'environment_mlcb': ${{ vars.testpropertymlcb }}"
          echo "Property testpropertymlcb2 should be 'environment_mlcb': ${{ vars.testpropertymlcb2 }}"
          echo "Property testpropertymlcb3 should be 'environment_mlcb': ${{ vars.testpropertymlcb3 }}"
          echo "Property testpropertymlcb4 should be 'environment_mlcb': ${{ vars.testpropertymlcb4 }}"
          echo "Property testpropertymlcb4 should be '***': ${{ secrets.testsecret1 }}"
          echo "Property testpropertymlcbONLYTOP should be 'CloudBees Preprod': ${{ vars.testpropertymlcbONLYTOP }}"
  